---
- name: Converge
  hosts: all
  vars:
    resource_monitor_packages: true
    network_monitor_packages: true
    terminal_packages: true
    shell_packages: true
    editor_packages: true

  pre_tasks:
    - name: Install Dependencies.
      yum: name=libselinux-python
      when: ansible_os_family == 'RedHat'
      changed_when: false

  roles:
    - role: ansible-role-sysadmin
